version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app-network

  server:
    build:
      context: ./backend
    ports:
      - 5000:5000
    networks:
      - app-network
    volumes:
      - ./source_dir:/app/server
    depends_on:
      - db
    command: npm run start
    restart: on-failure
    tty: true
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:example@db:5432/testing
      - JSONWEBTOKEN_KEY=test1234

networks:
  app-network:
    driver: bridge
