version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    networks:
      - app-network
    expose:
      - 6379
    ports:
      - 6379:6379
    command: redis-server

networks:
  app-network:
    driver: bridge
